baseURL = 'https://localhost:1313/Blog'
languageCode = 'en-us'
theme = 'anubis2'
title = 'Gaetano Dalius Ambrico'

[author]
name = "Gaetano Dalius Ambrico"
# email  = "mail@mail.mail"

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = 'About Me'
url = "/about"
weight = 3

[params]
readMore = true # true | false; Showing readmore link in the list of posts; default: false
# readNextPosts = 3 # Number of posts to show in the "Read Next" section; default: 3
colorTheme = "auto" # "auto" | "light" | "dark"; default: "auto"
colorThemeSwitcher = true # true | false; Showing color theme switcher in top of the site; default: false
toc = true # true | false; Showing table of contents in the post; default: true
# math = false # true | false; Enable MathJax; default: false; You can enable MathJax in the post by adding math: true in a post's metadata section.

# check more social icons at https://github.com/Junyi-99/hugo-theme-anubis2/wiki/Social-Icons
social = [
     { id="github", name="GaetanoDaliusAmbrico" },
     { id="linkedin", url="https://it.linkedin.com/in/gdambrico/" },
 ]

# rssIcon = true # true | false; Showing RSS icon; default: true

[taxonomies]
tag = "tags" # This allows you to use the "tags" in your markdown metadata

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

